name: CI

on:
  push:
    branches: [development, feature/*]
  pull_request:
    branches: [development]

jobs:
    lint-and-build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20'
            cache: 'npm'
            cache-dependency-path: ./backend/package-lock.json

        - name: Install dependencies
          working-directory: backend
          run: npm ci

        - name: Run Lint
          working-directory: backend
          run: npm run lint

        - name: Run Build
          working-directory: backend
          run: npm run build